name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Boost
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev

    
    - name: Build
      run: make
      
